# Generated by Django 6.0.3 on 2026-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Your Google App Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Your Google App Client Secret', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Current Access Token (can be left blank)', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Current Refresh Token (can be left blank)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Use these credentials as active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Credential',
                'verbose_name_plural': 'Google Credentials',
            },
        ),
    ]
